version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: "5000"
      MONGO_URI: "mongodb://mongo_db:27017/ChatApp"
      JWT_SECRET: "2019102hhzslla!"
    depends_on:
      - mongo_db

volumes:
  mongo_db:
