name: Mywebsite.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  builds:
    runs-on: self-hosted
     strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/**/package-lock.json"
      - run: npm ci
